### ISSUE TITLE
Unable to find opengl

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/photolayer_pi#14]
Using leamas workflow files. 

Adding these files to the linker allows the plugin to compile and work locally (VS2017).
opengl32.lib
glu32.lib

How to modify CMakeLists.txt or elsewhere to fix this?

Bad formatting in CML at the moment. Just going to fix this.

**Comment by Rasbats** [comment]
Thanks for the PRs. Massive leap forward. The Windows OpenGL to fix. Using frontend2 it produced a Windows tarball but .... that was then.

**Comment by Rasbats** [comment]
Notice that Weatherfax, which this plugin is based on, uses PluginGL.cmake. Should this be included? I added it to the cmake folder.

**Comment by leamas** [comment]
> The Windows OpenGL to fix

Fixed in next PR :)

**Comment by leamas** [comment]
>  Should this be included?

Probably not. It  builds without it, so there are seemingly no references to it. It could (should) be removed together with src/plugingl.


This is a beast, but in hindsight the changes doesn't look that bad....

**Comment by Rasbats** [comment]
I will look at plugingl shortly. Have tried a fix for the Mac build problem. Your work on this is fantastic.
BTW found this for removing my rubbish tags: `git push -d origin $(git tag -l "*v3*")`

**Comment by Rasbats** [comment]
Mac build problem remains. I will flash up my Mac Mini and see if a local compile throws any light on this.

**Comment by leamas** [comment]
hm... have you got a build log? It builds for me: https://app.circleci.com/pipelines/github/leamas/photolayer_pi/33/workflows/658b98fa-c269-42cc-9e0b-7fb099a34f2e

**Comment by leamas** [comment]
Ah... the MacOS fixes are in the last PR which you havn't  merged :)

**Comment by leamas** [comment]
>  found this for removing my rubbish tags: git push -d origin $(git tag -l "*v3*")

Hm... they have added some syntactic sugar to git... great!

**Comment by Rasbats** [comment]
Thanks for the MacOS fixes. Builds for Mac here as well!  About to test. 
Just tried to import the plugin with Ubuntu 20.04... Incompatible plugin detected.

**Comment by leamas** [comment]
And I discover that it doesn't build the flatpak plugin (missing geotiff dep). More work...

**Comment by Rasbats** [comment]
Maybe Ubuntu problem is that I was using the bionic version. Now upgrading.

**Comment by leamas** [comment]
When ion bionic, there are both gt2 and gtk3 variants. Which means that if main opencpn is gtk3, the plugins must also be gtk2. Or the other way around.

Focal is simpler, it's gtk3 only.

**Comment by Rasbats** [comment]
Ok... the gtk3 problem has gone away. Now trying to align Photolayer with ShipDriver. Splitting off the dependencies is great. Easy to see what dependencies are needed. mingw32 is causing me grief. I think it was left out before. Raising another issue for this.
